# Generated by Django 2.2.3 on 2019-07-10 08:36

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='英文简称')),
                ('fullDisplayName', models.CharField(db_index=True, max_length=255, verbose_name='中文全称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='URL地址')),
                ('config_xml', models.FileField(upload_to=data.models.project_filepath, verbose_name='config.xml')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Job名')),
                ('fullDisplayName', models.CharField(db_index=True, max_length=255, verbose_name='中文全称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='URL地址')),
                ('config_xml', models.FileField(upload_to=data.models.job_filepath, verbose_name='config.xml')),
                ('env', models.CharField(default='all', max_length=255, verbose_name='环境(组)')),
                ('nextBuildNumber', models.PositiveIntegerField(verbose_name='下次构建ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_project', to='data.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Job',
                'ordering': ('name', 'created_at'),
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_id', models.PositiveIntegerField(verbose_name='构建ID')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='URL地址')),
                ('result', models.CharField(choices=[(0, 'SUCCESS'), (1, 'FAILED')], max_length=1, verbose_name='执行结果')),
                ('fullDisplayName', models.CharField(db_index=True, max_length=255, verbose_name='中文全称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='构建时长')),
                ('consoleText', models.FileField(upload_to=data.models.build_filepath, verbose_name='构建console信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                (
                'job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_job', to='data.Job', verbose_name='所属Job')),
            ],
            options={
                'verbose_name': '构建',
                'verbose_name_plural': '构建',
                'ordering': ('build_id', 'created_at'),
                'unique_together': {('job', 'build_id')},
            },
        ),
        migrations.CreateModel(
            name='JobParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='参数名')),
                ('type', models.CharField(max_length=255, verbose_name='参数类型')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='参数值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_job', to='data.Job', verbose_name='所属Job')),
            ],
            options={
                'verbose_name': 'Job参数',
                'verbose_name_plural': 'Job参数',
                'ordering': ('name', 'created_at'),
                'unique_together': {('job', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BuildParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='参数名')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='参数值')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_build', to='data.Build',
                                            verbose_name='所属构建')),
            ],
            options={
                'verbose_name': '构建参数',
                'verbose_name_plural': '构建参数',
                'ordering': ('name', 'created_at'),
                'unique_together': {('build', 'name')},
            },
        ),
    ]
